// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfZp6Y7tekwwMWlcYiCfizYS9n9lY9ADc',
    appId: '1:744505086852:web:a9e0c372675bd8ca4283d1',
    messagingSenderId: '744505086852',
    projectId: 'fluttermovierestapiproject',
    authDomain: 'fluttermovierestapiproject.firebaseapp.com',
    storageBucket: 'fluttermovierestapiproject.appspot.com',
    measurementId: 'G-B7XSEZBSC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbcsJDSOr_giRq2Qsr13GTFZRiigTICtA',
    appId: '1:744505086852:android:896c729b85dfe9e44283d1',
    messagingSenderId: '744505086852',
    projectId: 'fluttermovierestapiproject',
    storageBucket: 'fluttermovierestapiproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ3SwfUHvHD5Jv27BYx_j18YR_sBhEfbM',
    appId: '1:744505086852:ios:52e83e02c0d79d644283d1',
    messagingSenderId: '744505086852',
    projectId: 'fluttermovierestapiproject',
    storageBucket: 'fluttermovierestapiproject.appspot.com',
    iosBundleId: 'com.example.projectForMovieWithApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ3SwfUHvHD5Jv27BYx_j18YR_sBhEfbM',
    appId: '1:744505086852:ios:e315294778e94e234283d1',
    messagingSenderId: '744505086852',
    projectId: 'fluttermovierestapiproject',
    storageBucket: 'fluttermovierestapiproject.appspot.com',
    iosBundleId: 'com.example.projectForMovieWithApi.RunnerTests',
  );
}
